name: kooginapp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  appwrite: ^12.0.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  timeago: ^3.6.1
  any_link_preview: ^3.0.1
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/svgs/

  